.PHONY: help install test test-e2e test-e2e-tls run worker db-up db-down db-logs ha-up ha-down ha-logs prod-up prod-down prod-logs prod-config migrate migrate-down migration db-backup db-restore clean ui-install ui-dev ui-run ui-build ui-test ui-clean vault-up vault-down vault-logs vault-smoke vault-audit-bootstrap ssh-ca-bootstrap pki-bootstrap transit-bootstrap e2e-up e2e-down e2e-logs mysql-tls-issue gitleaks pip-audit npm-audit bandit semgrep security backup-vault lockfiles evidence release-notes

PYTHON := .venv/bin/python
PYTEST := .venv/bin/pytest
UVICORN := .venv/bin/uvicorn
ALEMBIC := .venv/bin/alembic
CELERY := .venv/bin/celery

HOST ?= 127.0.0.1
PORT ?= 8000

help:
	@echo "Targets:"
	@echo "  install        Install project + dev dependencies into .venv"
	@echo "  test           Run pytest (fast suite — e2e bucket excluded by default)"
	@echo "  test-e2e       Run the Phase 2c CP5 e2e suite against docker sshd + Vault"
	@echo "  test-e2e-tls   Run the Phase 2d CP5 mTLS acceptance suite (live uvicorn + LocalDevPKI)"
	@echo "  e2e-up         Build + start the e2e sshd container (host port 2222)"
	@echo "  e2e-down       Stop the e2e sshd container and drop its volume"
	@echo "  e2e-logs       Tail the e2e sshd container logs"
	@echo "  run            Start the FastAPI app with uvicorn (HOST=$(HOST) PORT=$(PORT))"
	@echo "  worker         Start a Celery worker for the provisioning queue"
	@echo "  db-up          Start MySQL + Valkey via docker compose"
	@echo "  db-down        Stop MySQL + Valkey"
	@echo "  db-logs        Tail MySQL logs"
	@echo "  ha-up          Start the Phase 3d HA demo profile (2 API replicas + nginx LB)"
	@echo "  ha-down        Stop the HA demo profile"
	@echo "  ha-logs        Tail all HA profile services"
	@echo "  prod-up        Bring up the production single-host stack (api + worker + web + data tier)"
	@echo "  prod-down      Stop the production stack"
	@echo "  prod-logs      Tail every service in the production stack"
	@echo "  prod-config    Render the merged compose config for debugging"
	@echo "  migrate        Apply all pending Alembic migrations (alembic upgrade head)"
	@echo "  migrate-down   Roll back the most recent migration (alembic downgrade -1)"
	@echo "  migration m=.. Generate a new autogenerated revision (alembic revision --autogenerate -m ..)"
	@echo "  db-backup o=.. Dump all data to a JSON file (make db-backup o=backup.json)"
	@echo "  db-restore i=. Restore data from a JSON backup (make db-restore i=backup.json)"
	@echo "  ui-install     Install Next.js dashboard deps (npm install in web/)"
	@echo "  ui-dev         Start the Next.js dashboard on http://127.0.0.1:3100"
	@echo "                 (reads BFF mTLS config from web/.env.local — see web/.env.example)"
	@echo "  ui-run         Alias for ui-dev"
	@echo "  ui-build       Production build of the Next.js dashboard"
	@echo "  ui-test        Run dashboard unit tests (vitest)"
	@echo "  ui-clean       Remove dashboard build artefacts and node_modules"
	@echo "  vault-up       Start the dev Vault container (Phase 2a spike)"
	@echo "  vault-down     Stop the dev Vault container"
	@echo "  vault-logs     Tail the Vault container logs"
	@echo "  vault-smoke    Run scripts/vault_smoke.py against the dev Vault"
	@echo "  vault-audit-bootstrap"
	@echo "                 Enable a file audit device on the dev Vault (Phase 2e)"
	@echo "  backup-vault   Save a Vault raft snapshot to backups/vault/ (Phase 2e — production Vault only; see docs/runbooks/backup-restore.md)"
	@echo "  ssh-ca-bootstrap  Idempotently configure the Vault SSH CA (Phase 2c)"
	@echo "  pki-bootstrap  Idempotently configure the Vault PKI (Phase 2d)"
	@echo "  transit-bootstrap"
	@echo "                 Idempotently enable the Vault Transit engine + master key (Phase 2b)"
	@echo "  mysql-tls-issue  Mint the MySQL server cert + CA bundle into tls/mysql/"
	@echo "  gitleaks       Run gitleaks secret scan (Phase 2e CI gate)"
	@echo "  pip-audit      Run pip-audit against the synced Python deps"
	@echo "  npm-audit      Run npm audit --omit=dev against the dashboard deps"
	@echo "  bandit         Run bandit -ll over src/ (Python SAST)"
	@echo "  semgrep        Run semgrep p/python over src/"
	@echo "  security       Run every Phase 2e security gate locally"
	@echo "  lockfiles      Verify pyproject.toml/uv.lock + web/package*.json parity (Phase 2e cycle 3)"
	@echo "  evidence       Generate SOC 2-style evidence pack into evidence/ (Phase 2e cycle 4)"
	@echo "  release-notes  Preview the release-notes body for VERSION=vX.Y.Z (Phase 2f cycle 2)"
	@echo "  clean          Remove caches and build artifacts"

install:
	@if command -v uv >/dev/null 2>&1; then \
		echo "Using uv to install dependencies"; \
		uv pip install -e ".[dev]"; \
	else \
		echo "uv not found, bootstrapping pip via ensurepip"; \
		$(PYTHON) -m ensurepip --upgrade; \
		$(PYTHON) -m pip install -e ".[dev]"; \
	fi

test:
	$(PYTEST) -q

run:
	@if [ -z "$(TLS_CERT_PEM)" ] || [ -z "$(TLS_KEY_PEM)" ] || [ -z "$(TLS_CA_BUNDLE_PEM)" ]; then \
		echo "ERROR: TLS_CERT_PEM, TLS_KEY_PEM, and TLS_CA_BUNDLE_PEM must all be set."; \
		echo "       Quickest dev path:"; \
		echo "         alembic upgrade head"; \
		echo "         wg-manager operators add --cn dev-operator --role admin"; \
		echo "         wg-manager certs issue --type api --cn 127.0.0.1 \\"; \
		echo "           --out-cert tls/server.crt --out-key tls/server.key --out-chain tls/ca-bundle.crt"; \
		echo "         wg-manager certs issue --type cli --cn dev-operator \\"; \
		echo "           --out-cert tls/client.crt --out-key tls/client.key --out-chain tls/client.chain.crt"; \
		echo "         export TLS_REQUIRED=true TLS_CERT_PEM=tls/server.crt TLS_KEY_PEM=tls/server.key TLS_CA_BUNDLE_PEM=tls/ca-bundle.crt"; \
		echo "         make run"; \
		echo "       Production: see README 'Running with TLS' and docs/vault-cookbook.md §4."; \
		exit 2; \
	fi
	BIND_HOST=$(HOST) BIND_PORT=$(PORT) $(PYTHON) -m wg_manager

worker:
	$(CELERY) -A wg_manager.celery_app worker --loglevel=info

db-up:
	docker compose up -d

db-down:
	docker compose down

db-logs:
	docker compose logs -f mysql

# Phase 3d cycle 4a — HA control-plane demo profile. Brings up 2 API
# replicas + nginx TCP-passthrough LB on top of the existing data
# tier (mysql + valkey + vault + vector). See
# docs/deploy/ha-control-plane.md "Running the ha profile locally".
ha-up:
	docker compose --profile ha up -d --build

ha-down:
	docker compose --profile ha down

ha-logs:
	docker compose --profile ha logs -f --tail=100

# ---------------------------------------------------------------------------
# Production-shaped single-host stack (docker-compose.prod.yml).
#
# Brings up api + worker + web alongside the hardened mysql/valkey/vault
# overrides. Operator must have populated .env.prod from
# .env.prod.example BEFORE the first run — see
# docs/deploy/single-host-prod.md for the full bootstrap sequence.
#
# The targets explicitly load .env.prod via --env-file so the variables
# resolve regardless of the operator's shell state.
# ---------------------------------------------------------------------------
PROD_COMPOSE := docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml

prod-up:
	@if [ ! -f .env.prod ]; then \
		echo "ERROR: .env.prod is missing — copy .env.prod.example and fill in secrets first."; \
		echo "       See docs/deploy/single-host-prod.md for the bootstrap order."; \
		exit 2; \
	fi
	# Ensure vault-init.json exists as a FILE (not a directory) before
	# compose bind-mounts it. On first prod-up the file is empty;
	# bootstrap-substrate writes the generated unseal keys + root
	# token into it via `vault operator init`. Without this touch,
	# Docker silently creates a directory at the mount target — which
	# the script then can't write to.
	@touch vault-init.json
	@chmod 0600 vault-init.json
	# `--wait` blocks until every service reaches its target state
	# (`healthy` for long-runners, `exited 0` for the two bootstrap
	# containers). With the self-bootstrap services, that means the
	# command returns only once the stack is fully usable.
	$(PROD_COMPOSE) up -d --build --wait

prod-down:
	$(PROD_COMPOSE) down

prod-logs:
	$(PROD_COMPOSE) logs -f --tail=200

prod-config:
	$(PROD_COMPOSE) config

migrate:
	$(ALEMBIC) upgrade head

migrate-down:
	$(ALEMBIC) downgrade -1

migration:
	@if [ -z "$(m)" ]; then echo "usage: make migration m=\"short message\""; exit 2; fi
	$(ALEMBIC) revision --autogenerate -m "$(m)"

WG_MANAGER := .venv/bin/wg-manager

db-backup:
	@if [ -z "$(o)" ]; then echo "usage: make db-backup o=backup.json"; exit 2; fi
	$(WG_MANAGER) db backup --output "$(o)"

db-restore:
	@if [ -z "$(i)" ]; then echo "usage: make db-restore i=backup.json"; exit 2; fi
	$(WG_MANAGER) db restore --input "$(i)" --drop-existing

clean:
	rm -rf .pytest_cache build dist *.egg-info src/*.egg-info
	find . -type d -name __pycache__ -prune -exec rm -rf {} +

# ---------------------------------------------------------------------------
# Dashboard (web/) targets
# ---------------------------------------------------------------------------

NPM := npm

ui-install:
	cd web && $(NPM) install

ui-dev:
	cd web && $(NPM) run dev

ui-run: ui-dev

ui-build:
	cd web && $(NPM) run build

ui-test:
	cd web && $(NPM) run test

ui-clean:
	rm -rf web/.next web/node_modules web/coverage

# ---------------------------------------------------------------------------
# Vault (Phase 2a spike) — see docs/vault-cookbook.md
# ---------------------------------------------------------------------------

VAULT_ADDR ?= http://127.0.0.1:8200
VAULT_TOKEN ?= dev-only-root

vault-up:
	docker compose up -d vault

vault-down:
	docker compose stop vault

vault-logs:
	docker compose logs -f vault

vault-smoke:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/vault_smoke.py

# Phase 2e audit-log cycle 1 — enable a file audit device on the dev
# Vault. Idempotent: a re-run against an already-bootstrapped Vault is
# a no-op. The audit file lives in the wg_manager_vault_audit_logs
# named volume (mounted at /vault/logs/ on the container) so it
# survives compose restarts.
vault-audit-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/vault_audit_bootstrap.py

# Phase 2e backup cycle 2 — capture a Vault raft snapshot via the
# dev-container CLI. The snapshot lands at /vault/snapshots/<ts>.snap
# inside the container, which the docker-compose stack maps to the
# wg_manager_vault_audit_logs volume's sibling path on disk. Idempotent:
# every invocation produces a new timestamped file. Production
# operators run `vault operator raft snapshot save` directly against
# their Vault address; see docs/runbooks/backup-restore.md.
backup-vault:
	@mkdir -p backups/vault
	@ts=$$(date -u +%Y%m%dT%H%M%SZ); \
	docker compose exec -T -e VAULT_TOKEN=$(VAULT_TOKEN) vault \
		vault operator raft snapshot save /vault/logs/snap-$$ts.snap \
		&& docker compose cp vault:/vault/logs/snap-$$ts.snap backups/vault/snap-$$ts.snap \
		&& docker compose exec -T vault rm -f /vault/logs/snap-$$ts.snap \
		&& echo "snapshot written to backups/vault/snap-$$ts.snap"

# ---------------------------------------------------------------------------
# SSH CA (Phase 2c) — see docs/vault-cookbook.md §3
# ---------------------------------------------------------------------------

ssh-ca-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/ssh_ca_bootstrap.py

# ---------------------------------------------------------------------------
# PKI (Phase 2d) — see docs/vault-cookbook.md §4
# ---------------------------------------------------------------------------

pki-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/pki_bootstrap.py

# Phase 2b — enable Vault Transit engine + create the `wg-manager`
# master key with derived=True (required for the per-row context
# binding wg_manager.crypto enforces). Idempotent. The prod stack's
# self-bootstrap (`make prod-up`) runs this automatically.
transit-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/transit_bootstrap.py

# ---------------------------------------------------------------------------
# MySQL TLS (Phase 2d CP4.2) — mint the server cert into the bind-mount
# directory the docker-compose `mysql` service reads from. The op needs
# to run this before the first `make db-up` once CP4.2 is enabled; the
# my.cnf drop-in in docker/mysql/conf.d/wg-manager-tls.cnf refuses to
# let MySQL come up if the PEMs are missing.
# ---------------------------------------------------------------------------

mysql-tls-issue:
	@mkdir -p tls/mysql
	$(WG_MANAGER) certs issue --type mysql --cn localhost \
		--san localhost --san 127.0.0.1 --san mysql --san wg_manager_mysql \
		--ttl-days 30 \
		--out-cert tls/mysql/server.crt \
		--out-key tls/mysql/server.key \
		--out-chain tls/mysql/ca.crt

# ---------------------------------------------------------------------------
# Phase 2c CP5 — dockerised-sshd end-to-end suite
# ---------------------------------------------------------------------------
#
# The e2e suite needs both Vault dev (``make vault-up``) and the
# dedicated sshd container (``make e2e-up``) running. ``make
# test-e2e`` brings the sshd container up itself via the conftest
# fixture, but Vault must already be running. The fast suite (``make
# test``) stays hermetic and excludes the bucket via the ``-m 'not
# e2e'`` ``addopts`` in ``pyproject.toml``.

test-e2e:
	$(PYTEST) tests/e2e -m e2e --override-ini="addopts="

# ---------------------------------------------------------------------------
# Phase 2d CP5 — mTLS acceptance suite
# ---------------------------------------------------------------------------
#
# The TLS acceptance bucket sits under ``tests/e2e/tls/`` and spins
# its own live ``uvicorn`` subprocess with ``LocalDevPKI`` as the
# trust anchor. It does *not* need Vault or the sshd container — the
# only docker prerequisite is for the CP5.4 MySQL-rotation test,
# which the conftest gates on a reachable ``mysql`` compose service.
# ``--override-ini="addopts="`` neutralises the default ``-m 'not e2e
# and not e2e_tls'`` so the explicit ``-m e2e_tls`` selects in.

test-e2e-tls:
	$(PYTEST) tests/e2e/tls -m e2e_tls --override-ini="addopts="

e2e-up:
	docker compose --profile e2e up -d --build sshd-e2e

e2e-down:
	docker compose --profile e2e down -v sshd-e2e

e2e-logs:
	docker compose --profile e2e logs -f sshd-e2e

# ---------------------------------------------------------------------------
# Phase 2e — security gates
# ---------------------------------------------------------------------------
#
# Each gate has its own target so a developer can repro a single CI
# failure locally without paying the rest. ``make security`` runs the
# full set. Targets prefer a locally-installed binary and bail out with
# an install hint rather than silently no-op-ing.

gitleaks:
	@if ! command -v gitleaks >/dev/null 2>&1; then \
		echo "ERROR: gitleaks not installed."; \
		echo "       macOS:  brew install gitleaks"; \
		echo "       Linux:  https://github.com/gitleaks/gitleaks#installing"; \
		echo "       The CI workflow pins v8.30.1; match locally if you want byte-for-byte parity."; \
		exit 2; \
	fi
	gitleaks detect --source . --no-banner --redact

# pip-audit walks the synced .venv against PyPI's vulnerability feed.
# ``--ignore-vuln`` mirrors the CI workflow so a local repro matches.
# Update the ignore list in lockstep with .github/workflows/deps-audit.yml.
pip-audit:
	uv run --frozen --with pip-audit pip-audit --strict \
		--ignore-vuln CVE-2026-44405

npm-audit:
	cd web && npm audit --omit=dev --audit-level=high

# Bandit reads its config from [tool.bandit] in pyproject.toml — match
# the CI step exactly so a local repro is byte-for-byte.
bandit:
	uv run --frozen --with bandit bandit -ll -c pyproject.toml -r src/

# Semgrep p/python ruleset. ``--error`` flips findings into a non-zero
# exit so the gate behaves as a gate rather than a printout.
semgrep:
	uv run --frozen --with semgrep semgrep \
		--config=p/python --error --metrics=off src/

# Aggregate target. Order is cheapest-first so a fast failure short-
# circuits the rest. gitleaks/bandit are sub-second; the audits and
# semgrep are seconds-to-tens-of-seconds depending on caches.
security: gitleaks bandit pip-audit npm-audit semgrep

# Phase 2e reproducible-builds cycle 3 — verify pyproject.toml /
# uv.lock and web/package.json / web/package-lock.json haven't drifted
# apart. Matches the .github/workflows/lockfile.yml gate byte-for-byte
# so a local pre-push reproduces a CI failure without round-tripping
# through GitHub.
lockfiles:
	uv lock --check
	cd web && npm ci --dry-run

# Phase 2e cycle 4 — SOC 2-style evidence pack. Walks the auditevent
# table (last 30 days), the certificate + operator registries, and the
# Vault audit log slice into a tar.gz under evidence/. The output is
# timestamped so successive invocations don't clobber each other; an
# operator's cron drops them onto an external store via their own
# shipper. The default --vault-audit-log path matches the docker-
# compose vault service mount; production deployments override.
evidence:
	@mkdir -p evidence
	@ts=$$(date -u +%Y%m%dT%H%M%SZ); \
	$(WG_MANAGER) evidence pack \
		--output evidence/evidence-pack-$$ts.tar.gz \
		--since-days 30 \
		&& echo "evidence pack written to evidence/evidence-pack-$$ts.tar.gz"

# Phase 2f cycle 2 — preview the release-notes body the Release
# workflow would extract for a given tag. Operator-facing pre-flight
# check before `git push origin v<X.Y.Z>` fires the workflow. See
# docs/release.md for the full release walkthrough.
release-notes:
	@if [ -z "$(VERSION)" ]; then echo "usage: make release-notes VERSION=vX.Y.Z"; exit 2; fi
	$(PYTHON) scripts/extract_changelog.py "$(VERSION)"
