.PHONY: help install test test-e2e run worker db-up db-down db-logs migrate migrate-down migration db-backup db-restore clean ui-install ui-dev ui-run ui-build ui-test ui-clean vault-up vault-down vault-logs vault-smoke ssh-ca-bootstrap e2e-up e2e-down e2e-logs

PYTHON := .venv/bin/python
PYTEST := .venv/bin/pytest
UVICORN := .venv/bin/uvicorn
ALEMBIC := .venv/bin/alembic
CELERY := .venv/bin/celery

HOST ?= 127.0.0.1
PORT ?= 8000

help:
	@echo "Targets:"
	@echo "  install        Install project + dev dependencies into .venv"
	@echo "  test           Run pytest (fast suite — e2e bucket excluded by default)"
	@echo "  test-e2e       Run the Phase 2c CP5 e2e suite against docker sshd + Vault"
	@echo "  e2e-up         Build + start the e2e sshd container (host port 2222)"
	@echo "  e2e-down       Stop the e2e sshd container and drop its volume"
	@echo "  e2e-logs       Tail the e2e sshd container logs"
	@echo "  run            Start the FastAPI app with uvicorn (HOST=$(HOST) PORT=$(PORT))"
	@echo "  worker         Start a Celery worker for the provisioning queue"
	@echo "  db-up          Start MySQL + Valkey via docker compose"
	@echo "  db-down        Stop MySQL + Valkey"
	@echo "  db-logs        Tail MySQL logs"
	@echo "  migrate        Apply all pending Alembic migrations (alembic upgrade head)"
	@echo "  migrate-down   Roll back the most recent migration (alembic downgrade -1)"
	@echo "  migration m=.. Generate a new autogenerated revision (alembic revision --autogenerate -m ..)"
	@echo "  db-backup o=.. Dump all data to a JSON file (make db-backup o=backup.json)"
	@echo "  db-restore i=. Restore data from a JSON backup (make db-restore i=backup.json)"
	@echo "  ui-install     Install Next.js dashboard deps (npm install in web/)"
	@echo "  ui-dev         Start the Next.js dashboard on http://127.0.0.1:3000"
	@echo "  ui-run         Alias for ui-dev"
	@echo "  ui-build       Production build of the Next.js dashboard"
	@echo "  ui-test        Run dashboard unit tests (vitest)"
	@echo "  ui-clean       Remove dashboard build artefacts and node_modules"
	@echo "  vault-up       Start the dev Vault container (Phase 2a spike)"
	@echo "  vault-down     Stop the dev Vault container"
	@echo "  vault-logs     Tail the Vault container logs"
	@echo "  vault-smoke    Run scripts/vault_smoke.py against the dev Vault"
	@echo "  ssh-ca-bootstrap  Idempotently configure the Vault SSH CA (Phase 2c)"
	@echo "  clean          Remove caches and build artifacts"

install:
	@if command -v uv >/dev/null 2>&1; then \
		echo "Using uv to install dependencies"; \
		uv pip install -e ".[dev]"; \
	else \
		echo "uv not found, bootstrapping pip via ensurepip"; \
		$(PYTHON) -m ensurepip --upgrade; \
		$(PYTHON) -m pip install -e ".[dev]"; \
	fi

test:
	$(PYTEST) -q

run:
	$(UVICORN) wg_manager.main:app --host $(HOST) --port $(PORT) --reload

worker:
	$(CELERY) -A wg_manager.celery_app worker --loglevel=info

db-up:
	docker compose up -d

db-down:
	docker compose down

db-logs:
	docker compose logs -f mysql

migrate:
	$(ALEMBIC) upgrade head

migrate-down:
	$(ALEMBIC) downgrade -1

migration:
	@if [ -z "$(m)" ]; then echo "usage: make migration m=\"short message\""; exit 2; fi
	$(ALEMBIC) revision --autogenerate -m "$(m)"

WG_MANAGER := .venv/bin/wg-manager

db-backup:
	@if [ -z "$(o)" ]; then echo "usage: make db-backup o=backup.json"; exit 2; fi
	$(WG_MANAGER) db backup --output "$(o)"

db-restore:
	@if [ -z "$(i)" ]; then echo "usage: make db-restore i=backup.json"; exit 2; fi
	$(WG_MANAGER) db restore --input "$(i)" --drop-existing

clean:
	rm -rf .pytest_cache build dist *.egg-info src/*.egg-info
	find . -type d -name __pycache__ -prune -exec rm -rf {} +

# ---------------------------------------------------------------------------
# Dashboard (web/) targets
# ---------------------------------------------------------------------------

NPM := npm

ui-install:
	cd web && $(NPM) install

ui-dev:
	cd web && $(NPM) run dev

ui-run: ui-dev

ui-build:
	cd web && $(NPM) run build

ui-test:
	cd web && $(NPM) run test

ui-clean:
	rm -rf web/.next web/node_modules web/coverage

# ---------------------------------------------------------------------------
# Vault (Phase 2a spike) — see docs/vault-cookbook.md
# ---------------------------------------------------------------------------

VAULT_ADDR ?= http://127.0.0.1:8200
VAULT_TOKEN ?= dev-only-root

vault-up:
	docker compose up -d vault

vault-down:
	docker compose stop vault

vault-logs:
	docker compose logs -f vault

vault-smoke:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/vault_smoke.py

# ---------------------------------------------------------------------------
# SSH CA (Phase 2c) — see docs/vault-cookbook.md §7
# ---------------------------------------------------------------------------

ssh-ca-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/ssh_ca_bootstrap.py

# ---------------------------------------------------------------------------
# Phase 2c CP5 — dockerised-sshd end-to-end suite
# ---------------------------------------------------------------------------
#
# The e2e suite needs both Vault dev (``make vault-up``) and the
# dedicated sshd container (``make e2e-up``) running. ``make
# test-e2e`` brings the sshd container up itself via the conftest
# fixture, but Vault must already be running. The fast suite (``make
# test``) stays hermetic and excludes the bucket via the ``-m 'not
# e2e'`` ``addopts`` in ``pyproject.toml``.

test-e2e:
	$(PYTEST) tests/e2e -m e2e --override-ini="addopts="

e2e-up:
	docker compose --profile e2e up -d --build sshd-e2e

e2e-down:
	docker compose --profile e2e down -v sshd-e2e

e2e-logs:
	docker compose --profile e2e logs -f sshd-e2e
