.PHONY: help install test lint fmt shellcheck test-e2e test-e2e-tls run run-enroll worker beat db-up db-down db-logs ha-up ha-down ha-logs prod-up prod-down prod-logs prod-config migrate migrate-down migration db-backup prod-db-backup db-restore clean ui-install ui-dev ui-run ui-build ui-test ui-clean vault-up vault-down vault-logs vault-smoke vault-audit-bootstrap ssh-ca-bootstrap pki-bootstrap transit-bootstrap e2e-up e2e-down e2e-logs mysql-tls-issue certs-rotate certs-rotate-if-due host-export host-import db-counts vault-migrate-raft repl-primary-setup standby-up standby-down standby-seed standby-status standby-bundle standby-pull demote failover rejoin standby-metrics standby-drill alerts-check gitleaks pip-audit npm-audit bandit semgrep security backup-vault lockfiles evidence release-notes terraform-check

PYTHON := .venv/bin/python
PYTEST := .venv/bin/pytest
UVICORN := .venv/bin/uvicorn
ALEMBIC := .venv/bin/alembic
CELERY := .venv/bin/celery
RUFF := .venv/bin/ruff
SHELLCHECK := .venv/bin/shellcheck

HOST ?= 127.0.0.1
PORT ?= 8000

help:
	@echo "Targets:"
	@echo "  install        Create .venv and install project + dev deps (uv.lock pins via uv)"
	@echo "  test           Run pytest (fast suite — e2e bucket excluded by default)"
	@echo "  test-e2e       Run the Phase 2c CP5 e2e suite against docker sshd + Vault"
	@echo "  test-e2e-tls   Run the Phase 2d CP5 mTLS acceptance suite (live uvicorn + LocalDevPKI)"
	@echo "  lint           Run ruff (check only; rules in pyproject.toml [tool.ruff])"
	@echo "  shellcheck     Run shellcheck over every tracked *.sh file"
	@echo "  terraform-check  terraform fmt -check + validate deploy/terraform (Docker if no terraform)"
	@echo "  fmt            Apply ruff's safe auto-fixes (import order, unused imports, ...)"
	@echo "  e2e-up         Build + start the e2e sshd container (host port 2222)"
	@echo "  e2e-down       Stop the e2e sshd container and drop its volume"
	@echo "  e2e-logs       Tail the e2e sshd container logs"
	@echo "  run            Start the FastAPI app with uvicorn (HOST=$(HOST) PORT=$(PORT))"
	@echo "  run-enroll     Start the Phase 3f enrollment listener (server-auth TLS, ENROLL_BIND_PORT, default 8001)"
	@echo "  worker         Start a Celery worker for the provisioning queue"
	@echo "  beat           Start Celery beat (schedules the host-cert rotation sweep)"
	@echo "  db-up          Start MySQL + Valkey via docker compose"
	@echo "  db-down        Stop MySQL + Valkey"
	@echo "  db-logs        Tail MySQL logs"
	@echo "  ha-up          Start the Phase 3d HA demo profile (2 API replicas + nginx LB)"
	@echo "  ha-down        Stop the HA demo profile"
	@echo "  ha-logs        Tail all HA profile services"
	@echo "  prod-up        Bring up the production single-host stack (api + worker + web + data tier)"
	@echo "  prod-down      Stop the production stack"
	@echo "  prod-logs      Tail every service in the production stack"
	@echo "  prod-config    Render the merged compose config for debugging"
	@echo "  migrate        Apply all pending Alembic migrations (alembic upgrade head)"
	@echo "  migrate-down   Roll back the most recent migration (alembic downgrade -1)"
	@echo "  migration m=.. Generate a new autogenerated revision (alembic revision --autogenerate -m ..)"
	@echo "  db-backup o=.. Dump the dev DB (reads .env) to a JSON file (make db-backup o=backup.json)"
	@echo "  prod-db-backup  Encrypted dump of the production DB into backups/ (runs inside the prod stack)"
	@echo "  db-restore i=. Restore data from a JSON backup (make db-restore i=backup.json)"
	@echo "  ui-install     Install Next.js dashboard deps (npm install in web/)"
	@echo "  ui-dev         Start the Next.js dashboard on http://127.0.0.1:3100"
	@echo "                 (reads BFF mTLS config from web/.env.local — see web/.env.example)"
	@echo "  ui-run         Alias for ui-dev"
	@echo "  ui-build       Production build of the Next.js dashboard"
	@echo "  ui-test        Run dashboard unit tests (vitest)"
	@echo "  ui-clean       Remove dashboard build artefacts and node_modules"
	@echo "  vault-up       Start the dev Vault container (Phase 2a spike)"
	@echo "  vault-down     Stop the dev Vault container"
	@echo "  vault-logs     Tail the Vault container logs"
	@echo "  vault-smoke    Run scripts/vault_smoke.py against the dev Vault"
	@echo "  vault-audit-bootstrap"
	@echo "                 Enable a file audit device on the dev Vault (Phase 2e)"
	@echo "  backup-vault   Save a Vault raft snapshot to backups/vault/ (Phase 2e — production Vault only; see docs/runbooks/backup-restore.md)"
	@echo "  ssh-ca-bootstrap  Idempotently configure the Vault SSH CA (Phase 2c)"
	@echo "  pki-bootstrap  Idempotently configure the Vault PKI (Phase 2d)"
	@echo "  transit-bootstrap"
	@echo "                 Idempotently enable the Vault Transit engine + master key (Phase 2b)"
	@echo "  mysql-tls-issue  Mint the MySQL server cert + CA bundle into tls/mysql/"
	@echo "  certs-rotate   Re-mint MySQL + API + operator CLI certs and bounce mysql/api/worker/web"
	@echo "  certs-rotate-if-due  Run certs-rotate only if a TLS leaf is past half its lifetime (for a timer)"
	@echo "  host-export o=DIR  Bundle the STOPPED prod stack's volumes + secrets for a host move (docs/runbooks/host-migration.md)"
	@echo "  host-import i=DIR  Restore a host-export bundle onto this host (refuses to overwrite existing state)"
	@echo "  db-counts      Print exact per-table row counts from the prod MySQL (diff before/after a host move)"
	@echo "  repl-primary-setup  On the primary: create/refresh the MySQL replication user (docs/runbooks/standby-replication.md)"
	@echo "  standby-up     On the warm standby: run MySQL only, as a read-only replica"
	@echo "  standby-down   On the warm standby: stop the replica"
	@echo "  standby-seed primary=HOST  On the warm standby, once: copy the primary's DB and start replicating"
	@echo "  standby-status Replication + bundle health on the standby (exit 0 ok / 1 broken / 2 degraded)"
	@echo "  standby-bundle o=FILE|-  On the primary: Vault snapshot + vault-init.json/.env.prod/tls bundle for the standby"
	@echo "  standby-pull   On the warm standby (timer): fetch, verify and install the primary's bundle"
	@echo "  standby-metrics  On the standby (timer): write node_exporter textfile metrics (docs/observability.md)"
	@echo "  standby-drill  On the standby (weekly timer): restore the Vault snapshot into a throwaway Vault + check replication"
	@echo "  alerts-check   Validate + unit-test docs/observability/prometheus-alerts.yaml with promtool (docker)"
	@echo "  demote         On the primary: stop the app, make MySQL read-only (planned switchover, docs/runbooks/failover.md)"
	@echo "  failover       On the standby: fence, promote MySQL, restore Vault, become the primary [confirm=primary-is-down]"
	@echo "  rejoin primary=HOST  On the old primary: become a replica of HOST without re-seeding"
	@echo "  vault-migrate-raft  One-shot: convert the STOPPED prod Vault from file to raft storage (docs/runbooks/vault-raft-migration.md)"
	@echo "  gitleaks       Run gitleaks secret scan (Phase 2e CI gate)"
	@echo "  pip-audit      Run pip-audit against the synced Python deps"
	@echo "  npm-audit      Run npm audit --omit=dev against the dashboard deps"
	@echo "  bandit         Run bandit -ll over src/ (Python SAST)"
	@echo "  semgrep        Run semgrep p/python over src/"
	@echo "  security       Run every Phase 2e security gate locally"
	@echo "  lockfiles      Verify pyproject.toml/uv.lock + web/package*.json parity (Phase 2e cycle 3)"
	@echo "  evidence       Generate SOC 2-style evidence pack into evidence/ (Phase 2e cycle 4)"
	@echo "  release-notes  Preview the release-notes body for VERSION=vX.Y.Z (Phase 2f cycle 2)"
	@echo "  node-bootstrap VPN-first node enrollment — see scripts/wg_bootstrap.sh --help"
	@echo "  clean          Remove caches and build artifacts"

# Works on a fresh clone: both paths create .venv when it's missing.
# With uv this is the same command CI runs (the pinned versions in
# uv.lock). Without uv, pip resolves from pyproject.toml's ranges, so
# versions can drift from the lockfile; install uv for a reproducible env.
install:
	@if command -v uv >/dev/null 2>&1; then \
		echo "Using uv to sync .venv with uv.lock"; \
		uv sync --extra dev --frozen; \
	else \
		echo "uv not found, falling back to python3 -m venv + pip (versions not locked)"; \
		[ -x $(PYTHON) ] || python3 -m venv .venv; \
		$(PYTHON) -m pip install -e ".[dev]"; \
	fi

test:
	$(PYTEST) -q

# Lint gate — CI's lint job runs exactly this.
lint:
	$(RUFF) check .

# deploy/terraform: fmt -check, init (no backend) and validate. Needs
# registry access for providers; uses Docker when terraform isn't installed.
terraform-check:
	scripts/terraform_check.sh

# Every tracked *.sh, so a new script is linted without editing this target.
shellcheck:
	git ls-files -z '*.sh' | xargs -0 $(SHELLCHECK)

# Not `ruff format`: the codebase isn't formatter-clean yet (see the
# [tool.ruff.lint] comment in pyproject.toml).
fmt:
	$(RUFF) check --fix .

run:
	@if [ -z "$(TLS_CERT_PEM)" ] || [ -z "$(TLS_KEY_PEM)" ] || [ -z "$(TLS_CA_BUNDLE_PEM)" ]; then \
		echo "ERROR: TLS_CERT_PEM, TLS_KEY_PEM, and TLS_CA_BUNDLE_PEM must all be set."; \
		echo "       Quickest dev path:"; \
		echo "         alembic upgrade head"; \
		echo "         wg-manager operators add --cn dev-operator --role admin"; \
		echo "         wg-manager certs issue --type api --cn 127.0.0.1 \\"; \
		echo "           --out-cert tls/server.crt --out-key tls/server.key --out-chain tls/ca-bundle.crt"; \
		echo "         wg-manager certs issue --type cli --cn dev-operator \\"; \
		echo "           --out-cert tls/client.crt --out-key tls/client.key --out-chain tls/client.chain.crt"; \
		echo "         export TLS_REQUIRED=true TLS_CERT_PEM=tls/server.crt TLS_KEY_PEM=tls/server.key TLS_CA_BUNDLE_PEM=tls/ca-bundle.crt"; \
		echo "         make run"; \
		echo "       Production: see README 'Running with TLS' and docs/vault-cookbook.md §4."; \
		exit 2; \
	fi
	BIND_HOST=$(HOST) BIND_PORT=$(PORT) $(PYTHON) -m wg_manager

# Phase 3f spike: the cert-optional enrollment port. Reuses
# TLS_CERT_PEM / TLS_KEY_PEM; the runner refuses to start without them.
run-enroll:
	$(PYTHON) -m wg_manager.enroll_listener

worker:
	$(CELERY) -A wg_manager.celery_app worker --loglevel=info

beat:
	$(CELERY) -A wg_manager.celery_app beat --loglevel=info --schedule /tmp/wg-manager-celerybeat-schedule

# The dev stack's compose project. Without -p, compose names the project
# after the checkout directory, and the dev and prod checkouts are both
# called wg_manager: on a host that also runs prod, `make vault-up` or
# `make db-down` here would act on prod's containers. With its own
# project, a dev target on such a host fails on the container-name or
# port clash instead.
DEV_COMPOSE := docker compose -p wg_manager_dev

db-up:
	$(DEV_COMPOSE) up -d

db-down:
	$(DEV_COMPOSE) down

db-logs:
	$(DEV_COMPOSE) logs -f mysql

# Phase 3d cycle 4a — HA control-plane demo profile. Brings up 2 API
# replicas + nginx TCP-passthrough LB on top of the existing data
# tier (mysql + valkey + vault + vector). See
# docs/deploy/ha-control-plane.md "Running the ha profile locally".
ha-up:
	$(DEV_COMPOSE) --profile ha up -d --build

ha-down:
	$(DEV_COMPOSE) --profile ha down

ha-logs:
	$(DEV_COMPOSE) --profile ha logs -f --tail=100

# ---------------------------------------------------------------------------
# Production-shaped single-host stack (docker-compose.prod.yml).
#
# Brings up api + worker + web alongside the hardened mysql/valkey/vault
# overrides. Operator must have populated .env.prod from
# .env.prod.example BEFORE the first run — see
# docs/deploy/single-host-prod.md for the full bootstrap sequence.
#
# The targets explicitly load .env.prod via --env-file so the variables
# resolve regardless of the operator's shell state.
#
# .env.host (optional, gitignored, see .env.host.example) holds the
# settings that differ per host in a primary/standby pair (Phase 3d
# cycle 5b): WG_MANAGER_ROLE and MYSQL_BIND_ADDR. .env.prod is shared
# between the two hosts. When .env.host exists it's layered after
# .env.prod, so its values win.
# ---------------------------------------------------------------------------
HOST_ENV := $(wildcard .env.host)
# Pinned, not taken from the checkout's directory name: prod's
# containers and wg_manager_wg_manager_* volumes are named after it,
# and the dev stack (DEV_COMPOSE) must never share it.
PROD_PROJECT := wg_manager
PROD_COMPOSE := docker compose -p $(PROD_PROJECT) --env-file .env.prod $(if $(HOST_ENV),--env-file .env.host) -f docker-compose.yml -f docker-compose.prod.yml
# primary | standby | empty (single-host install).
HOST_ROLE := $(shell sed -n 's/^WG_MANAGER_ROLE=//p' .env.host 2>/dev/null | tr -d '"\047 ')
# Same stack without --env-file, for scripts that choose the env file
# themselves (migrate_host.sh import reads it from the bundle).
PROD_COMPOSE_BASE := docker compose -p $(PROD_PROJECT) -f docker-compose.yml -f docker-compose.prod.yml

prod-up:
	@# A standby runs mysql only. The full stack here would start a second
	@# beat racing the primary's host-cert renewals, and app writes would
	@# hit the read-only replica. Promotion is `make failover` (cycle 5d).
	@if [ "$(HOST_ROLE)" = standby ]; then \
		echo "ERROR: this host is the warm standby (WG_MANAGER_ROLE=standby in .env.host)."; \
		echo "       Use 'make standby-up'. To take over from the primary, use the failover runbook."; \
		exit 2; \
	fi
	@if [ ! -f .env.prod ]; then \
		echo "ERROR: .env.prod is missing — copy .env.prod.example and fill in secrets first."; \
		echo "       See docs/deploy/single-host-prod.md for the bootstrap order."; \
		exit 2; \
	fi
	# Ensure vault-init.json exists as a FILE (not a directory) before
	# compose bind-mounts it. On first prod-up the file is empty;
	# bootstrap-substrate writes the generated unseal keys + root
	# token into it via `vault operator init`. Without this touch,
	# Docker silently creates a directory at the mount target — which
	# the script then can't write to.
	#
	# Guarded on absence so re-runs are a no-op: after the first
	# prod-up the file is owned by the container's wgmanager user
	# (UID 1001), and a host-side touch/chmod as the operator's UID
	# would fail with EPERM. The container is the sole writer once
	# the file exists.
	@if [ ! -e vault-init.json ]; then \
		touch vault-init.json && chmod 0600 vault-init.json; \
	fi
	# `--wait` blocks until every service reaches its target state
	# (`healthy` for long-runners, `exited 0` for the two bootstrap
	# containers). With the self-bootstrap services, that means the
	# command returns only once the stack is fully usable.
	$(PROD_COMPOSE) up -d --build --wait

prod-down:
	$(PROD_COMPOSE) down

prod-logs:
	$(PROD_COMPOSE) logs -f --tail=200

prod-config:
	$(PROD_COMPOSE) config

# ---------------------------------------------------------------------------
# Cert rotation.
#
# Runs scripts/prod_rotate_certs.sh inside a bootstrap-app container
# (so the entrypoint shim sources VAULT_TOKEN) to re-mint the three
# short-TTL cert families the prod stack loads at startup:
#
#   * tls/mysql/{server,client}.{crt,key} — direct-to-Vault mint.
#   * tls/{server,ca-bundle}.{crt,key}    — API server cert.
#   * tls/{client,client.chain}.{crt,key} — operator CLI client cert.
#
# The mint script fixes the SEC1-vs-PKCS#8 EC-key trap that made the
# previous rotation cascade into MySQL "Unable to get private key"
# errors. After the mint we bounce every runtime container that
# holds cert material in memory — mysql (server.crt), api
# (server.crt + ca-bundle.crt), worker (client.crt), web (BFF's
# client.crt) — because none of them re-read the file otherwise.
# ---------------------------------------------------------------------------
certs-rotate:
	@if [ ! -f .env.prod ]; then \
		echo "ERROR: .env.prod is missing — cert rotation needs it for MYSQL_APP_PASSWORD, BOOTSTRAP_OPERATOR_CN, etc."; \
		exit 2; \
	fi
	$(PROD_COMPOSE) run --rm --entrypoint /usr/local/bin/entrypoint-wg-manager.sh bootstrap-app /app/scripts/prod_rotate_certs.sh
	@echo "==> Restarting mysql, api, worker, web to load fresh certs..."
	$(PROD_COMPOSE) restart mysql api worker web

# Hourly from a host systemd timer (docs/deploy/systemd-timer.md).
# Exits non-zero, without rotating, if the check itself fails.
certs-rotate-if-due:
	@PROD_COMPOSE="$(PROD_COMPOSE)" MAKE="$(MAKE)" scripts/certs_rotate_if_due.sh

# ---------------------------------------------------------------------------
# Host migration — cold copy of the prod stack to a new box.
# See docs/runbooks/host-migration.md for the full procedure.
# ---------------------------------------------------------------------------
host-export:
	@if [ -z "$(o)" ]; then echo "usage: make host-export o=DIR"; exit 2; fi
	@COMPOSE_BASE="$(PROD_COMPOSE_BASE)" scripts/migrate_host.sh export "$(o)"

host-import:
	@if [ -z "$(i)" ]; then echo "usage: make host-import i=DIR"; exit 2; fi
	@COMPOSE_BASE="$(PROD_COMPOSE_BASE)" scripts/migrate_host.sh import "$(i)"

db-counts:
	@COMPOSE_BASE="$(PROD_COMPOSE_BASE)" scripts/migrate_host.sh counts

# ---------------------------------------------------------------------------
# Warm standby — MySQL replication primary -> standby (Phase 3d cycle 5b).
# See docs/runbooks/standby-replication.md. Role-gated via .env.host:
# running the standby overlay on the primary would restart its mysqld
# read-only (an outage); running prod-up on the standby is refused above.
# ---------------------------------------------------------------------------
STANDBY_COMPOSE = $(PROD_COMPOSE) -f docker-compose.standby.yml

define require_standby_role
	@if [ "$(HOST_ROLE)" != standby ]; then \
		echo "ERROR: $@ runs on the warm standby only — set WG_MANAGER_ROLE=standby in .env.host there."; \
		exit 2; \
	fi
endef

# On the PRIMARY: create/refresh the X.509-only `wg_repl` user.
repl-primary-setup:
	@if [ "$(HOST_ROLE)" = standby ]; then \
		echo "ERROR: repl-primary-setup runs on the primary, and this host is the standby."; \
		exit 2; \
	fi
	@COMPOSE="$(PROD_COMPOSE)" scripts/mysql_replication.sh primary-setup

# On the STANDBY: run mysql only, as a read-only replica. Builds the
# wg-manager image first (Phase 3d cycle 5e): `make failover` and
# `make standby-drill` run it, and building it mid-outage would take
# minutes and need network access to the package indexes.
standby-up:
	$(require_standby_role)
	@if [ ! -f .env.prod ]; then echo "ERROR: .env.prod is missing — copy it from the primary."; exit 2; fi
	$(STANDBY_COMPOSE) build bootstrap-app
	$(STANDBY_COMPOSE) up -d --no-deps --wait mysql

standby-down:
	$(require_standby_role)
	$(STANDBY_COMPOSE) stop mysql

# On the STANDBY, once: copy the primary's DB and start replicating.
standby-seed:
	$(require_standby_role)
	@if [ -z "$(primary)" ]; then echo "usage: make standby-seed primary=<primary MySQL host, as named in MYSQL_SERVER_EXTRA_SANS>"; exit 2; fi
	@COMPOSE="$(STANDBY_COMPOSE)" scripts/mysql_replication.sh seed "$(primary)"

# On the STANDBY: replication health + the last pulled bundle. Exit 0
# healthy; 1 broken (replication down, nothing pulled); 2 degraded
# (replication lag over REPL_MAX_LAG_SECONDS, default 300; bundle older
# than STANDBY_MAX_BUNDLE_AGE_SECONDS, default 3600; or code drift from
# the primary). 1 wins over 2. Usable from a timer or monitor.
standby-status:
	@rc=0; \
	for check in "scripts/mysql_replication.sh status" "scripts/standby_pull.sh status"; do \
		COMPOSE="$(STANDBY_COMPOSE)" REPL_MAX_LAG_SECONDS="$(REPL_MAX_LAG_SECONDS)" $$check; r=$$?; \
		if [ $$r = 1 ]; then rc=1; elif [ $$r = 2 ] && [ $$rc = 0 ]; then rc=2; elif [ $$r -gt 2 ]; then rc=1; fi; \
		echo; \
	done; \
	exit $$rc

# ---------------------------------------------------------------------------
# Warm standby — shipping Vault + operator files (Phase 3d cycle 5c).
# ---------------------------------------------------------------------------

# On the PRIMARY (stack up): the bundle the standby pulls. o=- writes the
# tar to stdout, which is how `standby-pull` reads it over ssh. Every
# message from this target goes to stderr so stdout stays a clean tar.
standby-bundle:
	@if [ "$(HOST_ROLE)" = standby ]; then \
		echo "ERROR: standby-bundle runs on the primary, and this host is the standby." >&2; \
		exit 2; \
	fi
	@if [ -z "$(o)" ]; then echo "usage: make standby-bundle o=FILE|-" >&2; exit 2; fi
	@COMPOSE="$(PROD_COMPOSE)" scripts/standby_bundle.sh "$(o)"

# On the STANDBY (from a timer): fetch + verify + install the bundle.
standby-pull:
	$(require_standby_role)
	@COMPOSE="$(STANDBY_COMPOSE)" scripts/standby_pull.sh pull

# ---------------------------------------------------------------------------
# Watching + drilling the standby (Phase 3d cycle 5e).
# ---------------------------------------------------------------------------

# On the STANDBY, every minute (timer): node_exporter textfile metrics.
standby-metrics:
	$(require_standby_role)
	@COMPOSE="$(STANDBY_COMPOSE)" scripts/standby_metrics.sh

# On the STANDBY, weekly (timer): restore the latest Vault snapshot into an
# isolated throwaway Vault + check replication. Touches nothing real.
standby-drill:
	$(require_standby_role)
	@COMPOSE="$(STANDBY_COMPOSE)" scripts/standby_drill.sh

# Anywhere: validate + unit-test the Prometheus alert rules with promtool.
alerts-check:
	@PYTHON="$(PYTHON)" scripts/alerts_check.sh

# ---------------------------------------------------------------------------
# Promotion (Phase 3d cycle 5d) — docs/runbooks/failover.md.
# A switchover is: `demote` (old primary) -> `failover` (standby) ->
# `rejoin primary=HOST` (old primary). After an outage, skip `demote` and
# pass confirm=primary-is-down to `failover`.
# ---------------------------------------------------------------------------
demote:
	@if [ "$(HOST_ROLE)" != primary ]; then \
		echo "ERROR: demote runs on the primary (WG_MANAGER_ROLE=primary in .env.host)."; \
		exit 2; \
	fi
	@COMPOSE="$(PROD_COMPOSE)" MAKE="$(MAKE)" scripts/failover.sh demote

failover:
	$(require_standby_role)
	@COMPOSE="$(STANDBY_COMPOSE)" MAKE="$(MAKE)" CONFIRM="$(confirm)" scripts/failover.sh failover

rejoin:
	@if [ -z "$(primary)" ]; then echo "usage: make rejoin primary=<the new primary's MySQL host, e.g. general.vpn>"; exit 2; fi
	@if [ -z "$(HOST_ROLE)" ]; then echo "ERROR: rejoin needs .env.host (a primary/standby pair)."; exit 2; fi
	@COMPOSE="$(PROD_COMPOSE)" MAKE="$(MAKE)" scripts/failover.sh rejoin "$(primary)"

# One-shot file -> raft storage conversion for a prod Vault that predates
# Phase 3d cycle 5. Stack must be stopped. See
# docs/runbooks/vault-raft-migration.md.
vault-migrate-raft:
	@COMPOSE_BASE="$(PROD_COMPOSE_BASE)" scripts/vault_migrate_raft.sh

migrate:
	$(ALEMBIC) upgrade head

migrate-down:
	$(ALEMBIC) downgrade -1

migration:
	@if [ -z "$(m)" ]; then echo "usage: make migration m=\"short message\""; exit 2; fi
	$(ALEMBIC) revision --autogenerate -m "$(m)"

WG_MANAGER := .venv/bin/wg-manager

db-backup:
	@if [ -z "$(o)" ]; then echo "usage: make db-backup o=backup.json"; exit 2; fi
	$(WG_MANAGER) db backup --output "$(o)"

# Production DB backup. `db-backup` runs on the host with settings from
# the dev `.env`, so it can't reach the prod MySQL. This runs the same
# CLI inside a one-off bootstrap-app container, which has the prod
# DATABASE_URL and (via the entrypoint shim) the Vault token that
# --encrypt needs for Transit. The container user (UID 1001) can't
# write into backups/, so the envelope is streamed back over stdout
# (row counts go to stderr) into a 0600 file; a failed run removes the
# partial file so backups/ only ever holds complete dumps.
prod-db-backup:
	@if [ ! -f .env.prod ]; then echo "ERROR: .env.prod is missing — prod-db-backup targets the production stack."; exit 2; fi
	@mkdir -p backups
	@out="backups/wg-$$(date -u +%Y%m%dT%H%M%SZ).enc.json"; umask 077; \
	if $(PROD_COMPOSE) run --rm -T --entrypoint /usr/local/bin/entrypoint-wg-manager.sh bootstrap-app \
		sh -c 'wg-manager db backup --encrypt --output /tmp/backup.enc.json >&2 && cat /tmp/backup.enc.json' > "$$out.partial"; then \
		mv "$$out.partial" "$$out" && echo "==> encrypted backup written to $$out"; \
	else rc=$$?; rm -f "$$out.partial"; echo "ERROR: prod-db-backup failed (exit $$rc); no backup written." >&2; exit $$rc; fi

db-restore:
	@if [ -z "$(i)" ]; then echo "usage: make db-restore i=backup.json"; exit 2; fi
	$(WG_MANAGER) db restore --input "$(i)" --drop-existing

clean:
	rm -rf .pytest_cache build dist *.egg-info src/*.egg-info
	find . -type d -name __pycache__ -prune -exec rm -rf {} +

# ---------------------------------------------------------------------------
# Dashboard (web/) targets
# ---------------------------------------------------------------------------

NPM := npm

ui-install:
	cd web && $(NPM) install

ui-dev:
	cd web && $(NPM) run dev

ui-run: ui-dev

ui-build:
	cd web && $(NPM) run build

ui-test:
	cd web && $(NPM) run test

ui-clean:
	rm -rf web/.next web/node_modules web/coverage

# ---------------------------------------------------------------------------
# Vault (Phase 2a spike) — see docs/vault-cookbook.md
# ---------------------------------------------------------------------------

VAULT_ADDR ?= http://127.0.0.1:8200
VAULT_TOKEN ?= dev-only-root

vault-up:
	$(DEV_COMPOSE) up -d vault

vault-down:
	$(DEV_COMPOSE) stop vault

vault-logs:
	$(DEV_COMPOSE) logs -f vault

vault-smoke:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/vault_smoke.py

# Phase 2e audit-log cycle 1 — enable a file audit device on the dev
# Vault. Idempotent: a re-run against an already-bootstrapped Vault is
# a no-op. The audit file lives in the wg_manager_vault_audit_logs
# named volume (mounted at /vault/logs/ on the container) so it
# survives compose restarts.
vault-audit-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/vault_audit_bootstrap.py

# Phase 2e backup cycle 2 — capture a Vault raft snapshot via the
# dev-container CLI. The snapshot lands at /vault/snapshots/<ts>.snap
# inside the container, which the docker-compose stack maps to the
# wg_manager_vault_audit_logs volume's sibling path on disk. Idempotent:
# every invocation produces a new timestamped file. Production
# operators run `vault operator raft snapshot save` directly against
# their Vault address; see docs/runbooks/backup-restore.md.
backup-vault:
	@mkdir -p backups/vault
	@ts=$$(date -u +%Y%m%dT%H%M%SZ); \
	$(DEV_COMPOSE) exec -T -e VAULT_TOKEN=$(VAULT_TOKEN) vault \
		vault operator raft snapshot save /vault/logs/snap-$$ts.snap \
		&& $(DEV_COMPOSE) cp vault:/vault/logs/snap-$$ts.snap backups/vault/snap-$$ts.snap \
		&& $(DEV_COMPOSE) exec -T vault rm -f /vault/logs/snap-$$ts.snap \
		&& echo "snapshot written to backups/vault/snap-$$ts.snap"

# ---------------------------------------------------------------------------
# SSH CA (Phase 2c) — see docs/vault-cookbook.md §3
# ---------------------------------------------------------------------------

ssh-ca-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/ssh_ca_bootstrap.py

# ---------------------------------------------------------------------------
# PKI (Phase 2d) — see docs/vault-cookbook.md §4
# ---------------------------------------------------------------------------

pki-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/pki_bootstrap.py

# Phase 2b — enable Vault Transit engine + create the `wg-manager`
# master key with derived=True (required for the per-row context
# binding wg_manager.crypto enforces). Idempotent. The prod stack's
# self-bootstrap (`make prod-up`) runs this automatically.
transit-bootstrap:
	VAULT_ADDR=$(VAULT_ADDR) VAULT_TOKEN=$(VAULT_TOKEN) \
		$(PYTHON) scripts/transit_bootstrap.py

# ---------------------------------------------------------------------------
# MySQL TLS (Phase 2d CP4.2) — mint the server cert into the bind-mount
# directory the docker-compose `mysql` service reads from. The op needs
# to run this before the first `make db-up` once CP4.2 is enabled; the
# my.cnf drop-in in docker/mysql/conf.d/wg-manager-tls.cnf refuses to
# let MySQL come up if the PEMs are missing.
# ---------------------------------------------------------------------------

mysql-tls-issue:
	@mkdir -p tls/mysql
	$(WG_MANAGER) certs issue --type mysql --cn localhost \
		--san localhost --san 127.0.0.1 --san mysql --san wg_manager_mysql \
		--ttl-days 30 \
		--out-cert tls/mysql/server.crt \
		--out-key tls/mysql/server.key \
		--out-chain tls/mysql/ca.crt

# ---------------------------------------------------------------------------
# Phase 2c CP5 — dockerised-sshd end-to-end suite
# ---------------------------------------------------------------------------
#
# The e2e suite needs both Vault dev (``make vault-up``) and the
# dedicated sshd container (``make e2e-up``) running. ``make
# test-e2e`` brings the sshd container up itself via the conftest
# fixture, but Vault must already be running. The fast suite (``make
# test``) stays hermetic and excludes the bucket via the ``-m 'not
# e2e'`` ``addopts`` in ``pyproject.toml``.

test-e2e:
	$(PYTEST) tests/e2e -m e2e --override-ini="addopts="

# ---------------------------------------------------------------------------
# Phase 2d CP5 — mTLS acceptance suite
# ---------------------------------------------------------------------------
#
# The TLS acceptance bucket sits under ``tests/e2e/tls/`` and spins
# its own live ``uvicorn`` subprocess with ``LocalDevPKI`` as the
# trust anchor. It does *not* need Vault or the sshd container — the
# only docker prerequisite is for the CP5.4 MySQL-rotation test,
# which the conftest gates on a reachable ``mysql`` compose service.
# ``--override-ini="addopts="`` neutralises the default ``-m 'not e2e
# and not e2e_tls'`` so the explicit ``-m e2e_tls`` selects in.

test-e2e-tls:
	$(PYTEST) tests/e2e/tls -m e2e_tls --override-ini="addopts="

e2e-up:
	$(DEV_COMPOSE) --profile e2e up -d --build sshd-e2e

e2e-down:
	$(DEV_COMPOSE) --profile e2e down -v sshd-e2e

e2e-logs:
	$(DEV_COMPOSE) --profile e2e logs -f sshd-e2e

# ---------------------------------------------------------------------------
# Phase 2e — security gates
# ---------------------------------------------------------------------------
#
# Each gate has its own target so a developer can repro a single CI
# failure locally without paying the rest. ``make security`` runs the
# full set. Targets prefer a locally-installed binary and bail out with
# an install hint rather than silently no-op-ing.

gitleaks:
	@if ! command -v gitleaks >/dev/null 2>&1; then \
		echo "ERROR: gitleaks not installed."; \
		echo "       macOS:  brew install gitleaks"; \
		echo "       Linux:  https://github.com/gitleaks/gitleaks#installing"; \
		echo "       The CI workflow pins v8.30.1; match locally if you want byte-for-byte parity."; \
		exit 2; \
	fi
	@# --log-opts=HEAD: scan the current branch's history only, not every
	@# local branch (gitleaks defaults to git log --all). Mirrors CI.
	gitleaks detect --source . --no-banner --redact --log-opts=HEAD

# pip-audit walks the synced .venv against PyPI's vulnerability feed.
# ``--ignore-vuln`` mirrors the CI workflow so a local repro matches.
# Update the ignore list in lockstep with .github/workflows/deps-audit.yml.
pip-audit:
	uv run --frozen --with pip-audit pip-audit --strict \
		--ignore-vuln CVE-2026-44405

npm-audit:
	cd web && npm audit --omit=dev --audit-level=high

# Bandit reads its config from [tool.bandit] in pyproject.toml — match
# the CI step exactly so a local repro is byte-for-byte.
bandit:
	uv run --frozen --with bandit bandit -ll -c pyproject.toml -r src/

# Semgrep p/python ruleset. ``--error`` flips findings into a non-zero
# exit so the gate behaves as a gate rather than a printout.
semgrep:
	uv run --frozen --with semgrep semgrep \
		--config=p/python --error --metrics=off src/

# Aggregate target. Order is cheapest-first so a fast failure short-
# circuits the rest. gitleaks/bandit are sub-second; the audits and
# semgrep are seconds-to-tens-of-seconds depending on caches.
security: gitleaks bandit pip-audit npm-audit semgrep

# Phase 2e reproducible-builds cycle 3 — verify pyproject.toml /
# uv.lock and web/package.json / web/package-lock.json haven't drifted
# apart. Matches the .github/workflows/lockfile.yml gate byte-for-byte
# so a local pre-push reproduces a CI failure without round-tripping
# through GitHub.
lockfiles:
	uv lock --check
	cd web && npm ci --dry-run

# Phase 2e cycle 4 — SOC 2-style evidence pack. Walks the auditevent
# table (last 30 days), the certificate + operator registries, and the
# Vault audit log slice into a tar.gz under evidence/. The output is
# timestamped so successive invocations don't clobber each other; an
# operator's cron drops them onto an external store via their own
# shipper. The default --vault-audit-log path matches the docker-
# compose vault service mount; production deployments override.
evidence:
	@mkdir -p evidence
	@ts=$$(date -u +%Y%m%dT%H%M%SZ); \
	$(WG_MANAGER) evidence pack \
		--output evidence/evidence-pack-$$ts.tar.gz \
		--since-days 30 \
		&& echo "evidence pack written to evidence/evidence-pack-$$ts.tar.gz"

# Phase 2f cycle 2 — preview the release-notes body the Release
# workflow would extract for a given tag. Operator-facing pre-flight
# check before `git push origin v<X.Y.Z>` fires the workflow. See
# docs/release.md for the full release walkthrough.
release-notes:
	@if [ -z "$(VERSION)" ]; then echo "usage: make release-notes VERSION=vX.Y.Z"; exit 2; fi
	$(PYTHON) scripts/extract_changelog.py "$(VERSION)"

# ---------------------------------------------------------------------------
# Node enrollment — VPN-first bootstrap (scripts/wg_bootstrap.sh)
# ---------------------------------------------------------------------------
# The `wg_node` Cinc cookbook was retired in favour of scripts/wg_bootstrap.sh,
# which joins a node to the VPN via the API first and only then bootstraps
# Cinc over the tunnel (so the Cinc server need not be public-facing). The
# script takes per-run SSH/API/cert arguments, so it is invoked directly
# rather than through a fixed make target:
#
#   scripts/wg_bootstrap.sh --help
#   scripts/wg_bootstrap.sh all --target <node> --api-url <url> --server-id <id> ...
